---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'HellUpLine Uploader Application'

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
          - Label: {default: 'Application Parameters'}
            Parameters:
              - KeyPrefix
          - Label: {default: 'Api Parameters'}
            Parameters:
              - AcmCertificateArn
              - DomainName

Parameters:
    KeyPrefix:
        Description: 'Prefix used in s3 bucket to store user files'
        Type: String
        Default: 'user-files'
    AcmCertificateArn:
        Description: 'The ARN of the SSL certificate to use for the ApiGateway.'
        Type: String
    DomainName:
        Description: 'The application domain name.'
        Type: String

Mappings: {}

Conditions: {}

Resources:
    #
    # Functions
    #
    ListObjectsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: objects_api
            Handler: list_objects.lambda_handler
            Runtime: python3.7
            Timeout: 3
            Environment:
                Variables:
                    TABLE_NAME: !Ref UploadTable
            Events:
                CreateObjectd:
                    Type: Api
                    Properties:
                        Path: /objects
                        Method: GET
                        RestApiId: !Ref RestApi
                        Auth:
                            Authorizer: CognitoAuthorizer
            Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'dynamodb:Query'
                    Resource:
                      - !GetAtt UploadTable.Arn

    CreateObjectFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: objects_api
            Handler: create_object.lambda_handler
            Runtime: python3.7
            Timeout: 3
            Environment:
                Variables:
                    BUCKET_NAME: !Ref UploadBucket
                    KEY_PREFIX: !Ref KeyPrefix
                    TABLE_NAME: !Ref UploadTable
            Events:
                CreateObjectd:
                    Type: Api
                    Properties:
                        Path: /objects
                        Method: POST
                        RestApiId: !Ref RestApi
                        Auth:
                            Authorizer: CognitoAuthorizer
            Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'dynamodb:PutItem'
                    Resource:
                      - !GetAtt UploadTable.Arn
                  - Effect: Allow
                    Action:
                      - 's3:PutObject'
                    Resource:
                      - !Sub '${UploadBucket.Arn}/${KeyPrefix}/*'
    #
    # Api
    #
    RestApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Cors:
                AllowMethods: "'OPTIONS,HEAD,GET,POST,PATCH,PUT,DELETE'"
                AllowHeaders: "'X-Forwarded-For,Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                AllowOrigin: "'*'"
                MaxAge: "'600'"
                AllowCredentials: "'true'"
            Auth:
                # DefaultAuthorizer: CognitoAuthorizer
                Authorizers:
                    CognitoAuthorizer:
                        UserPoolArn: !GetAtt UserPool.Arn
            MethodSettings:
              - HttpMethod: '*'
                ResourcePath: '/*'
                LoggingLevel: INFO
                DataTraceEnabled: true
                MetricsEnabled: true

    RestApiDomainName:
        Type: AWS::ApiGateway::DomainName
        Properties:
            CertificateArn: !Ref AcmCertificateArn
            DomainName: !Ref DomainName

    RestApiPathMapping:
        Type: AWS::ApiGateway::BasePathMapping
        Properties:
            DomainName: !Ref RestApiDomainName
            RestApiId: !Ref RestApi
            Stage: Prod

    #
    # Storage
    #
    UploadBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
            AccessControl: Private
            PublicAccessBlockConfiguration:
                BlockPublicAcls: True
                BlockPublicPolicy: True
                IgnorePublicAcls: True
                RestrictPublicBuckets: True
            CorsConfiguration:
                CorsRules:
                  - Id: SignedUrlLambda
                    AllowedMethods: ['GET', 'POST', 'PUT']
                    AllowedHeaders: ['*']
                    AllowedOrigins: ['*']
                    ExposedHeaders: ['ContentType', 'Date']
                    MaxAge: 3600
            LifecycleConfiguration:
                Rules:
                  - Id: IncompleteUploads
                    Status: Enabled
                    AbortIncompleteMultipartUpload:
                        DaysAfterInitiation: 5

    UploadTable:
        Type: AWS::DynamoDB::Table
        Properties:
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
              # - {AttributeName: 'storage_key', AttributeType: 'S'}
              - {AttributeName: 'user_id', AttributeType: 'S'}
              - {AttributeName: 'filename', AttributeType: 'S'}
            KeySchema:
              - {AttributeName: 'user_id', KeyType: 'HASH'}
              - {AttributeName: 'filename', KeyType: 'RANGE'}
            # GlobalSecondaryIndexes:
            #   - IndexName: 'storage'
            #     KeySchema:
            #       - {AttributeName: 'storage_key', KeyType: 'HASH'}
            #     Projection:
            #         NonKeyAttributes:
            #           - 'user_id'
            #           - 'filename'
            #         ProjectionType: INCLUDE

    #
    # Authentication
    #
    UserPool:
        Type: AWS::Cognito::UserPool
        # Properties:
        #     AdminCreateUserConfig:
        #         AllowAdminCreateUserOnly: true
        #         UnusedAccountValidityDays: 30
        #         InviteMessageTemplate:
        #             EmailMessage: 'Your username is {username} and temporary password is {####}.'
        #             EmailSubject: 'Your temporary password'
        #     SmsConfiguration:
        #         ExternalId: !Sub '${AWS::StackName}-external'
        #         SnsCallerArn: !GetAtt SMSRole.Arn
        #     SmsVerificationMessage: 'Your verification code is {####}.'
        #     SmsAuthenticationMessage: 'Your authentication code is {####}.'
        #     EmailConfiguration:
        #         ReplyToEmailAddress: donotreply@domain.tld
        #         EmailSendingAccount: COGNITO_DEFAULT
        #     EmailVerificationMessage: 'Your verification code is {####}.'
        #     EmailVerificationSubject: 'Your verification code'
        #     MfaConfiguration: 'OPTIONAL'
        #     AutoVerifiedAttributes:
        #       - email
        #     UsernameAttributes:
        #       - email
        #     Policies:
        #         PasswordPolicy:
        #             MinimumLength: 12
        #             RequireLowercase: true
        #             RequireNumbers: true
        #             RequireSymbols: true
        #             RequireUppercase: true
        #     Schema:
        #       - AttributeDataType: String
        #         Name: email
        #         Mutable: false
        #         Required: true
        #       - AttributeDataType: String
        #         Name: name
        #         StringAttributeConstraints:
        #             MaxLength: 255
        #             MinLength: 6
        #         Mutable: true
        #         Required: true

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref UserPool
        GenerateSecret: false
        ExplicitAuthFlows:
            - USER_PASSWORD_AUTH

    # SMSRole:
    #     Type: AWS::IAM::Role
    #     Properties:
    #         AssumeRolePolicyDocument:
    #             Version: '2012-10-17'
    #             Statement:
    #               - Effect: 'Allow'
    #                 Principal: {Service: ['cognito-idp.amazonaws.com'] }
    #                 Action: ['sts:AssumeRole']
    #         Policies:
    #           - PolicyName: cognito-sns-sms
    #             PolicyDocument:
    #                 Version: '2012-10-17'
    #                 Statement:
    #                   - Effect: 'Allow'
    #                     Action:
    #                       - 'sns:publish'
    #                     Resource:
    #                       - '*'


Outputs:
    EndpointDomainName:
        Description: 'API Gateway endpoint URL for Prod stage'
        # Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
        Value: !Sub 'https://${DomainName}'

    # Functions
    ListObjectsFunction:
        Description: 'Get Upload URL Lambda Function ARN'
        Value: !GetAtt ListObjectsFunction.Arn
    ListObjectsFunctionIamRole:
        Description: 'Implicit IAM Role created for ListObjectsFunction'
        Value: !GetAtt ListObjectsFunctionRole.Arn
    CreateObjectdFunction:
        Description: 'Get Upload URL Lambda Function ARN'
        Value: !GetAtt CreateObjectFunction.Arn
    CreateObjectdFunctionIamRole:
        Description: 'Implicit IAM Role created for CreateObjectFunction'
        Value: !GetAtt CreateObjectFunctionRole.Arn

    # Storage
    UploadBucket:
        Description: 'Bucket where files are stored'
        Value: !Ref UploadBucket
    UploadTable:
        Description: 'Table where metadata are stored'
        Value: !Ref UploadTable

    # Authentication
    UserPoolId:
        Value: !Ref UserPool
    UserPoolClientId:
        Value: !Ref UserPoolClient
