---
version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
    pre_build:
        commands:
          - npm --prefix ./website ci
    build:
        commands:
          - jq -Mf ./website/generate-settings.jq < "${CODEBUILD_SRC_DIR_ApplicationCloudFormationOutputsAsZip}/ApplicationOutputs.json" | tee ./website/src/settings.json
          - npm --prefix ./website run build

artifacts:
    base-directory: ./website/build
    files:
      - '**/*'

cache:
    paths:
        - ./website/node_modules/
