---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'HellUpLine Uploader CodePipeline'

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
          - Label: {default: 'Stack Parameters'}
            Parameters:
              - ParentStackName
          - Label: {default: 'Application Parameters'}
            Parameters:
              - ApplicationAcmCertificateArn
              - ApplicationDomainName
          - Label: {default: 'Website Parameters'}
            Parameters:
              - WebsiteBucket
          - Label: {default: 'Github Parameters'}
            Parameters:
              - GithubToken
              - GithubUser
              - GithubRepo
              - GithubBranch

Parameters:
    ParentStackName:
        Description: 'Parent Stack Name'
        Type: String
    GithubToken:
        Type: 'AWS::SSM::Parameter::Value<String>'
        Description: 'Github OAuth Token with full permissions on admin:repo_hook and repo'
        Default: '/github/token/hellupline'
    GithubUser:
        Type: String
        Description: 'Github user where the repository lives'
    GithubRepo:
        Type: String
        Description: 'Gitub repository name'
    GithubBranch:
        Type: String
        Description: 'Gitub repository branch'
    ApplicationAcmCertificateArn:
        Description: 'The ARN of the SSL certificate to use for the CloudFront distribution.'
        Type: String
    ApplicationDomainName:
        Description: 'The website domain name.'
        Type: String
    WebsiteBucket:
        Description: 'Bucket for Website static files'
        Type: String

Mappings: {}

Conditions: {}

Resources:
    Pipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            RoleArn: !GetAtt CodePipelineRole.Arn
            ArtifactStore:
                Location: '{{resolve:ssm:/artifacts-store:1}}'
                Type: S3
            Stages:
              - Name: Source
                Actions:
                  - Name: SourceGithub
                    ActionTypeId:
                        Category: Source
                        Owner: ThirdParty
                        Provider: GitHub
                        Version: '1'
                    Configuration:
                        Owner: !Ref GithubUser
                        Repo: !Ref GithubRepo
                        Branch: !Ref GithubBranch
                        OAuthToken: !Ref GithubToken
                    OutputArtifacts:
                      - Name: SourceCodeAsZip
                    RunOrder: 1
              - Name: ApplicationBuild
                Actions:
                  - Name: ApplicationCodeBuild
                    ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Provider: CodeBuild
                        Version: '1'
                    Configuration:
                        ProjectName: !Ref ApplicationCodeBuildProject
                    InputArtifacts:
                      - Name: SourceCodeAsZip
                    OutputArtifacts:
                      - Name: ApplicationBuildArtifactAsZip
                    RunOrder: 1
              - Name: ApplicationDeploy
                Actions:
                  - Name: ApplicationCloudformation
                    ActionTypeId:
                        Category: Deploy
                        Owner: AWS
                        Provider: CloudFormation
                        Version: '1'
                    Configuration:
                        ActionMode: CREATE_UPDATE
                        Capabilities: CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM
                        RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                        StackName: !Sub '${ParentStackName}-application'
                        TemplatePath: ApplicationBuildArtifactAsZip::packaged.yaml
                        OutputFileName: ApplicationOutputs.json
                        ParameterOverrides: !Sub |
                            {
                                "AcmCertificateArn": "${ApplicationAcmCertificateArn}",
                                "DomainName": "${ApplicationDomainName}"
                            }
                    InputArtifacts:
                      - Name: ApplicationBuildArtifactAsZip
                    OutputArtifacts:
                      - Name: ApplicationCloudFormationOutputsAsZip
                    RunOrder: 1
              - Name: WebsiteBuild
                Actions:
                  - Name: WebsiteCodeBuild
                    ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Provider: CodeBuild
                        Version: '1'
                    Configuration:
                        ProjectName: !Ref WebsiteCodeBuildProject
                        PrimarySource: SourceCodeAsZip
                    InputArtifacts:
                      - Name: SourceCodeAsZip
                      - Name: ApplicationCloudFormationOutputsAsZip
                    OutputArtifacts:
                      - Name: WebsiteBuildArtifactAsZip
                    RunOrder: 1
              - Name: WebsiteDeploy
                Actions:
                  - Name: WebsiteBucket
                    ActionTypeId:
                        Category: Deploy
                        Owner: AWS
                        Provider: S3
                        Version: '1'
                    Configuration:
                        BucketName: !Ref WebsiteBucket
                        Extract: true
                    InputArtifacts:
                      - Name: WebsiteBuildArtifactAsZip
                    RunOrder: 1

    PipelineWebhook:
        Type: AWS::CodePipeline::Webhook
        Properties:
            TargetPipeline: !Ref Pipeline
            TargetPipelineVersion: !GetAtt Pipeline.Version
            TargetAction: SourceGithub
            RegisterWithThirdParty: true
            Authentication: GITHUB_HMAC
            AuthenticationConfiguration:
                SecretToken: !Ref GithubToken
            Filters:
              - JsonPath: "$.ref"
                MatchEquals: refs/heads/{Branch}

    CodePipelineRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal: {Service: ['codepipeline.amazonaws.com']}
                    Action: ['sts:AssumeRole']
            Path: /
            ManagedPolicyArns:
                - '{{resolve:ssm:/managed-policies/artifacts-store:1}}'
                - '{{resolve:ssm:/managed-policies/logs:1}}'
            Policies:
              - PolicyName: iam
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'iam:PassRole'
                        Resource:
                          - !GetAtt CloudFormationExecutionRole.Arn
              - PolicyName: codebuild
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'codebuild:BatchGetBuilds'
                          - 'codebuild:StartBuild'
                        Resource:
                          - !Sub '${ApplicationCodeBuildProject.Arn}'
                          - !Sub '${WebsiteCodeBuildProject.Arn}'
              - PolicyName: application-cloudformation
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'cloudformation:DescribeStacks'
                          - 'cloudformation:CreateStack'
                          - 'cloudformation:UpdateStack'
                          - 'cloudformation:DeleteStack'
                        Resource:
                          - !Sub 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ParentStackName}-application/*'
              - PolicyName: website-bucket
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - 's3:GetObject'
                          - 's3:PutObject'
                          - 's3:DeleteObject'
                        Resource:
                          - !Sub 'arn:${AWS::Partition}:s3:::${WebsiteBucket}/*'

    CloudFormationExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal: {Service: ['cloudformation.amazonaws.com']}
                    Action: ['sts:AssumeRole']
            ManagedPolicyArns:
                - '{{resolve:ssm:/managed-policies/artifacts-store:1}}'
                - '{{resolve:ssm:/managed-policies/logs:1}}'
            Policies:
              - PolicyName: cloudformation
                PolicyDocument:
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'cloudformation:CreateChangeSet'
                        Resource:
                            - !Sub 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31'
              - PolicyName: iam
                PolicyDocument:
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'iam:AttachRolePolicy'
                          - 'iam:CreateRole'
                          - 'iam:UpdateRole'
                          - 'iam:DeleteRole'
                          - 'iam:DeleteRolePolicy'
                          - 'iam:DetachRolePolicy'
                          - 'iam:GetRole'
                          - 'iam:PassRole'
                          - 'iam:PutRolePolicy'
                        Resource:
                          - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ParentStackName}-*'
              - PolicyName: lambda
                PolicyDocument:
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'lambda:*'
                        Resource:
                          - !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${ParentStackName}-*'
              - PolicyName: api-gateway
                PolicyDocument:
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'apigateway:GET'
                          - 'apigateway:POST'
                          - 'apigateway:PATCH'
                          - 'apigateway:PUT'
                          - 'apigateway:DELETE'
                        Resource:
                          - !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}::/domainnames'
                          - !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}::/domainnames/*'
                          - !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}::/restapis'
                          - !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}::/restapis/*'
              - PolicyName: cloudfront
                PolicyDocument:
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'cloudfront:UpdateDistribution'
                        Resource:
                          - '*'

    ApplicationCodeBuildProject:
        Type: AWS::CodeBuild::Project
        Properties:
            ServiceRole: !GetAtt CodeBuildServiceRole.Arn
            Source:
                Type: CODEPIPELINE
                BuildSpec: application/buildspec.yaml
            Artifacts:
                Type: CODEPIPELINE
            Environment:
                Type: LINUX_CONTAINER
                ComputeType: BUILD_GENERAL1_SMALL
                Image: aws/codebuild/standard:2.0
                EnvironmentVariables:
                  - {Name: BUILD_OUTPUT_BUCKET, Value: '{{resolve:ssm:/artifacts-store:1}}'}
                  - {Name: BUILD_OUTPUT_PREFIX, Value: !Sub '${AWS::StackName}/application-cf-packages'}

    WebsiteCodeBuildProject:
        Type: AWS::CodeBuild::Project
        Properties:
            ServiceRole: !GetAtt CodeBuildServiceRole.Arn
            Source:
                Type: CODEPIPELINE
                BuildSpec: website/buildspec.yaml
            Artifacts:
                Type: CODEPIPELINE
            Environment:
                Type: LINUX_CONTAINER
                ComputeType: BUILD_GENERAL1_SMALL
                Image: aws/codebuild/standard:2.0
            Cache:
                Type: S3
                Location: !Sub "{{resolve:ssm:/artifacts-store:1}}/${AWS::StackName}/website-codebuild-cache"

    CodeBuildServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal: {Service: ['codebuild.amazonaws.com']}
                    Action: ['sts:AssumeRole']
            Path: /
            ManagedPolicyArns:
                - '{{resolve:ssm:/managed-policies/artifacts-store:1}}'
                - '{{resolve:ssm:/managed-policies/logs:1}}'

Outputs: {}
